# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /testgit/HelloWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /testgit/HelloWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /testgit/HelloWorld/CMakeFiles /testgit/HelloWorld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /testgit/HelloWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named test_say_hello

# Build rule for target.
test_say_hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_say_hello
.PHONY : test_say_hello

# fast build rule for target.
test_say_hello/fast:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/build
.PHONY : test_say_hello/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/main.c.s
.PHONY : src/main.c.s

src/say_hello.o: src/say_hello.c.o

.PHONY : src/say_hello.o

# target to build an object file
src/say_hello.c.o:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/src/say_hello.c.o
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/say_hello.c.o
.PHONY : src/say_hello.c.o

src/say_hello.i: src/say_hello.c.i

.PHONY : src/say_hello.i

# target to preprocess a source file
src/say_hello.c.i:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/src/say_hello.c.i
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/say_hello.c.i
.PHONY : src/say_hello.c.i

src/say_hello.s: src/say_hello.c.s

.PHONY : src/say_hello.s

# target to generate assembly for a file
src/say_hello.c.s:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/src/say_hello.c.s
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/say_hello.c.s
.PHONY : src/say_hello.c.s

test/test_say_hello.o: test/test_say_hello.c.o

.PHONY : test/test_say_hello.o

# target to build an object file
test/test_say_hello.c.o:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/test/test_say_hello.c.o
.PHONY : test/test_say_hello.c.o

test/test_say_hello.i: test/test_say_hello.c.i

.PHONY : test/test_say_hello.i

# target to preprocess a source file
test/test_say_hello.c.i:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/test/test_say_hello.c.i
.PHONY : test/test_say_hello.c.i

test/test_say_hello.s: test/test_say_hello.c.s

.PHONY : test/test_say_hello.s

# target to generate assembly for a file
test/test_say_hello.c.s:
	$(MAKE) -f CMakeFiles/test_say_hello.dir/build.make CMakeFiles/test_say_hello.dir/test/test_say_hello.c.s
.PHONY : test/test_say_hello.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clean-all"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... test_say_hello"
	@echo "... helloworld"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/say_hello.o"
	@echo "... src/say_hello.i"
	@echo "... src/say_hello.s"
	@echo "... test/test_say_hello.o"
	@echo "... test/test_say_hello.i"
	@echo "... test/test_say_hello.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

